name: Auto Creating Tags

on:
  push:
    branches:
    - master
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  TZ: Asia/Shanghai


jobs:
  build:
    name: Auto Creating Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Code
        uses: actions/checkout@v2

      - name: Create tag
        run:
          script: |
            for file in `find contrib -name go.mod`; do
                prefix=$(dirname $file)
                echo "refs/tags/${prefix}/${github.ref}"
            done


